//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClayApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class User: Entity
    {
        public User()
        {
            this.Door = new HashSet<Door>();
            this.DoorAccess = new HashSet<DoorAccess>();
            this.DoorAccessLog = new HashSet<DoorAccessLog>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual ICollection<Door> Door { get; set; }
        public virtual ICollection<DoorAccess> DoorAccess { get; set; }
        public virtual ICollection<DoorAccessLog> DoorAccessLog { get; set; }
    }
}
