//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClayApplication.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorAccessLog
    {
        public int doorid { get; set; }
        public int userid { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> state { get; set; }
        public int id { get; set; }
        public Nullable<bool> accessdenied { get; set; }
    
        public virtual Door Door { get; set; }
        public virtual User User { get; set; }
    }
}
